nodeLinker: node-modules

npmScopes:
  venuedevops:
    npmAlwaysAuth: true
    npmAuthToken: "${GITLAB_AUTH_TOKEN}"
    npmRegistryServer: "https://gitlab.adaptavist.net/api/v4/packages/npm/"

packageExtensions:
  "@venuedevops/venue-theme@*":
    dependencies:
      "@material-ui/core": "*"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
